### PR TITLE
fix(snap): Don't normalize paths for equality

### LINKED ISSUE #119: Snapbox 0.3.1 Breaking Change in `\` normalization
0.3.1 of Snapbox was a breaking change for me—as I'm using it to compare some generated TOML [here](https://github.com/knope-dev/knope/runs/7665020792?check_suite_focus=true). The `\` in these cases are not path separators, so should not be normalized.

If this is intentional, I can just replace my usage of `assert_eq_path` with a custom `Assert` that disables normalization—but I wanted to report the issue just in case it was unintentional.

Thanks!

### PR DESCRIPTION
**Pull request by epage**
Fixes #119

### CODE REVIEW

File: crates/snapbox/src/assert.rs [hunk 1]
```diff
@@ -187,7 +187,7 @@ impl Assert {
 
         actual = actual
             .try_coerce(format)
-            .map_text(|s| self.normalize_text(s));
+            .map_text(|s| crate::utils::normalize_lines(s));
```
Comment (Muscraft) [inline crates/snapbox/src/assert.rs:190]: I updated the [structured data issue](#92) to include `Normalize::Text` not just `Normalize::Newlines` so that we don't run into this issue again.
