### PR TITLE
fix: overwrite command status with TRYCMD=overwrite

### LINKED ISSUE #142: TRYCMD=overwrite should specify the command as failing if it fails during the run
That is, it should insert (or update) `? ERROR_CODE` in the test.

### PR DESCRIPTION
**Pull request by figsoda**
fixes #142

### CODE REVIEW

File: src/schema.rs [hunk 1]
```diff
@@ -125,13 +126,26 @@ impl TryCmd {
...
+                if let Some(code) = exit.and_then(|status| status.code()) {
+                    let raw = std::fs::read_to_string(path)
+                        .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
+                    let mut doc = raw
+                        .parse::<toml_edit::Document>()
+                        .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
+                    doc["status"] = toml_edit::value(toml_edit::InlineTable::default());
+                    doc["status"]["code"] = toml_edit::value(code as i64);
+                    std::fs::write(path, doc.to_string())
+                        .map_err(|e| format!("Failed to write {}: {}", path.display(), e))?;
```
Comment (epage) [inline src/schema.rs:147]: Looks like this unconditionally uses the code.  I feel like we should preserve the users existing style.

File: src/schema.rs [hunk 2]
```diff
@@ -142,17 +156,31 @@ impl TryCmd {
...
                         .expect("always present for .trycmd");
-                    let mut stdout = stdout.render().expect("at least Text");
-                    // Add back trailing newline removed when parsing
-                    stdout.push('\n');
+
                     let raw = std::fs::read_to_string(path)
                         .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
                     let mut normalized = snapbox::utils::normalize_lines(&raw);
+
+                    if let Some(code) = dbg!(exit).and_then(|status| status.code()) {
```
Comment (epage) [inline src/schema.rs:168]: `dbg` left in the code

File: src/schema.rs [hunk 3]
```diff
@@ -142,17 +156,31 @@ impl TryCmd {
...
+                        let status = &format!("? {code}");
```
Comment (epage) [inline src/schema.rs:169]: ditto about preserving style

File: src/schema.rs [hunk 4]
```diff
@@ -125,13 +126,26 @@ impl TryCmd {
         id: Option<&str>,
         stdout: Option<&crate::Data>,
         stderr: Option<&crate::Data>,
+        exit: Option<ExitStatus>,
     ) -> Result<(), crate::Error> {
         if let Some(ext) = path.extension() {
             if ext == std::ffi::OsStr::new("toml") {
```
Comment (epage) [inline src/schema.rs:132]: We should have tests for both toml and trycmd files

**Review by epage — COMMENTED** [review]
Thanks!

File: src/schema.rs (hunk 4 above)
Comment (figsoda) [reply src/schema.rs:132]: Do you know how to create `ExitStatus` reliably? I tried [ExitStatusExt::from_raw](https://doc.rust-lang.org/std/os/unix/process/trait.ExitStatusExt.html#tymethod.from_raw) but it doesn't work as expected since this is for waited statuses

Comment (figsoda) [reply src/schema.rs:133]: I was able to construct `ExitStatus` in hacky way and added some unit tests for the status overwriting features

File: src/schema.rs [hunk 5]
```diff
@@ -142,17 +154,28 @@ impl TryCmd {
...
+                        exit,
+                        step.expected_status,
+                        step.expected_status_source,
+                        &mut line_nums,
+                        &mut normalized,
+                    )?;
+
+                    let mut stdout = stdout.render().expect("at least Text");
+                    // Add back trailing newline removed when parsing
+                    stdout.push('\n');
```
Comment (epage) [inline src/schema.rs:176]: I feel like these are handling things at the wrong place

File: src/schema.rs [hunk 6]
```diff
@@ -352,10 +378,115 @@ fn overwrite_toml_output(
...
+) -> Result<(), snapbox::Error> {
+    if let Some(status) = exit {
+        if let Some(status) = if let Some(code) = status.code() {
+            if status.success() {
+                if let (true, Some(line_num)) = (
+                    expected_status != Some(CommandStatus::Success),
+                    expected_status_source,
+                ) {
+                    replace_lines(normalized, line_num..line_num + 1, "")?;
+                    *line_nums = line_nums.start - 1..line_nums.end - 1;
```
Comment (epage) [inline src/schema.rs:454]: Why do we need to change these?

File: src/schema.rs [hunk 7]
```diff
@@ -5,6 +5,8 @@
 use snapbox::{NormalizeNewlines, NormalizePaths};
 use std::collections::BTreeMap;
 use std::collections::VecDeque;
+use std::ops::Range;
+use std::process::ExitStatus;
```
Comment (epage) [inline src/schema.rs:9]: I tend to prefer that items are accessed by absolute path

File: src/schema.rs [hunk 8]
```diff
@@ -1255,4 +1396,156 @@ $ rust-cmd1
...
+        )
+        .unwrap();
+        assert_eq!(expected, actual);
+    }
+
+    #[test]
+    fn overwrite_toml_status_keeps_style() {
+        let expected = r#"
+bin.name = "cmd"
+status.code= 1
```
Comment (epage) [inline src/schema.rs:1438]: The toml formatting is off, it should be ` = ` (leading space)

File: src/schema.rs [hunk 9]
```diff
@@ -352,10 +378,115 @@ fn overwrite_toml_output(
...
+                    }
+                    _ => None,
+                }
+            }
+        } else if expected_status == Some(CommandStatus::Interrupted) {
+            None
+        } else {
+            Some("? interrupted".into())
+        } {
+            if let Some(line_num) = expected_status_source {
```
Comment (epage) [inline src/schema.rs:473]: imo this is too complicated of an expression

File: src/schema.rs [hunk 10]
```diff
@@ -352,10 +378,115 @@ fn overwrite_toml_output(
...
+    {
+        doc["status"] = toml_edit::value("interrupted");
+    }
+
+    Ok(doc.to_string())
+}
+
+fn overwrite_trycmd_status(
+    exit: Option<ExitStatus>,
+    expected_status: Option<CommandStatus>,
```
Comment (epage) [inline src/schema.rs:441]: Is this to save us from re-parsing the line?

How bad would it be to do that?  From a code clarify perspective, it feels weird that we are trusting to correctly pass in the correct piece of information rather than using what is already passed in

**Review by epage — COMMENTED** [review]
Thanks for continuing to move this forward!

The summary of my feedback is that this PR tends towards very complicated instructions that make it hard to read and would be hard to edit/debug in the future.

File: src/schema.rs (hunk 8 above)
Comment (figsoda) [reply src/schema.rs:1438]: I did that intentionally to make sure this preserves style

Comment (epage) [reply src/schema.rs:1438]: Oh yes, the `actual` also has it.  Stood out to me because that is a specific case that is easy to mess up with `toml_edit` :).  A more clear way might be to have a comment.

Comment (epage) [reply src/schema.rs:1438]: (granted, comments are likely to be invalidated by a change in the value)

File: src/schema.rs (hunk 6 above)
Comment (figsoda) [reply src/schema.rs:454]: since we deleted one line, the stdout overwrites need to be shifted upwards by one line

File: src/schema.rs [hunk 11]
```diff
@@ -352,10 +378,115 @@ fn overwrite_toml_output(
...
+                        doc["status"].get("code"),
+                        Some(toml_edit::Item::Value(toml_edit::Value::Integer(ref expected)))
+                            if expected.value() == &code)
+                    {
+                        doc["status"]["code"] = toml_edit::value(code);
+                    }
+                }
+                _ => {
+                    doc["status"] = toml_edit::value(toml_edit::InlineTable::default());
+                    doc["status"]["code"] = toml_edit::value(code);
```
[the remark this answers is not in the document]
Comment (figsoda) [reply src/schema.rs]: `None` should be valid here. There might be other values that are unreachable but I don't think we need to throw errors here

File: src/schema.rs (hunk 5 above)
Comment (figsoda) [reply src/schema.rs:174]: I'm not sure what you mean by that, it was originally there for the stdout overwrite, I just moved it down with the other stdout code

File: src/schema.rs (hunk 10 above)
Comment (figsoda) [reply src/schema.rs:448]: > Is this to save us from re-parsing the line?

Yes

I can combine `expected_status` and `expected_status_source` into one parameter `step` and use `parse_trycmd` in the tests if you think it is a better way to do it

File: src/schema.rs (hunk 6 above)
Comment (epage) [reply src/schema.rs]: If `line_nums` is specifically the lines for stdout, maybe we should put that in the name?

I also feel like either a function or at least parenthesis are needed as the formatting makes it look like the range is `1..line_nums.end`

File: src/schema.rs (hunk 10 above)
Comment (epage) [reply src/schema.rs:448]: Not looking too closely at the code, I lean towards that direction but if things end up being messier from it, I can understand.  Its just a direction I lean

File: src/schema.rs [hunk 12]
```diff
@@ -450,41 +450,48 @@ fn overwrite_trycmd_status(
...
-                        Some(format!("? {code}"))
-                    }
-                    _ => None,
-                }
+    let status = match exit {
+        Some(status) => status,
+        _ => {
+            return Ok(());
+        }
+    };
```
Comment (epage) [inline src/schema.rs:458]: Side note: when we upgrade MSRV, this can be simplified with let-else

Comment (figsoda) [reply src/schema.rs:458]: yep that's what I was originally using and got hit by the CI

File: src/schema.rs [hunk 13]
```diff
@@ -352,10 +378,115 @@ fn overwrite_toml_output(
     Ok(())
 }
 
+fn overwrite_toml_status(status: ExitStatus, raw: String) -> Result<String, toml_edit::TomlError> {
+    let mut doc = raw.parse::<toml_edit::Document>()?;
+    if let Some(code) = status.code() {
+        if status.success() {
+            if match doc.get("status") {
```
[the remark this answers is not in the document]
Comment (epage) [reply src/schema.rs]: Thanks, this clean up helped a lot!

File: src/schema.rs (hunk 9 above)
Comment (epage) [reply src/schema.rs]: Thanks!  This clean up helped a lot!

File: src/schema.rs (hunk 5 above)
Comment (epage) [reply src/schema.rs:174]: Ah, missed that.

File: src/schema.rs (hunk 12 above)
Comment (epage) [reply src/schema.rs:458]: Recently got to use it in another project and it was really handy: https://github.com/gitext-rs/git2-ext/blob/55616965732cc4ff6d63191bbd226b530e8c7e59/src/ops.rs#L634,L647

File: src/schema.rs [hunk 14]
```diff
@@ -450,41 +450,48 @@ fn overwrite_trycmd_status(
...
+                    Some(format!("? {code}"))
+                }
+                _ => None,
             }
         }
+    } else if expected_status == Some(CommandStatus::Interrupted) {
+        None
+    } else {
+        Some("? interrupted".into())
+    };
```
[the remark this answers is not in the document]
Comment (figsoda) [reply src/schema.rs:485]: I would prefer this as well, but clippy gives me [collapsible_else_if](https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if)

File: src/schema.rs (hunk 6 above)
Comment (figsoda) [reply src/schema.rs]: The default formatting with no spaces is a bit confusing, I have added the parenthesis for ranges

File: src/schema.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (epage) [reply src/schema.rs:485]: As I said, I am fine with marking that as `allow` in `lib.rs`

[the remark this answers is not in the document]
Comment (figsoda) [reply src/schema.rs:485]: Accidently skipped reading a line, sorry

File: src/schema.rs (hunk 10 above)
Comment (figsoda) [reply src/schema.rs]: Switched to `step` and also figured out I have been missing the fences for trycmd tests the whole time

File: src/schema.rs (hunk 12 above)
Comment (figsoda) [reply src/schema.rs:451]: Was able to use that in another project too: https://github.com/nix-community/patsh/commit/d7740b8f39677b6e8a73af38da8debcdf93babcc, makes stuff a lot more readable

**Comment by epage** [comment]
Thanks for all your work through this!

**Comment by figsoda** [comment]
Thanks!
